# Generated by Django 3.2.15 on 2022-08-18 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance', models.IntegerField(choices=[(1, '出席'), (2, '欠席')], verbose_name='出欠')),
                ('reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='欠席理由')),
                ('respon', models.TextField(blank=True, max_length=1000, null=True, verbose_name='返信')),
                ('child', models.ManyToManyField(to='app.Child', verbose_name='お子様の名前')),
            ],
        ),
    ]
