# Generated by Django 3.2.15 on 2022-08-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='child',
        ),
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.child', verbose_name='お子様の名前'),
            preserve_default=False,
        ),
    ]
